name: Robot Framework CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Create results directory
      run: |
        mkdir -p test-results
        
    - name: Run Robot Framework Tests
      run: |
        robot --variable BROWSER:headlesschrome --outputdir test-results Assignment-1-2-4/web/TestCase/Checkout.robot
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: test-results/
        
  download-results:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: robot-results
          path: test-results
          
      - name: List Downloaded Files
        run: |
          ls -la test-results/ 