name: Robot Framework CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      
    - name: Start ChromeDriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        
    - name: Run Robot Framework Tests
      run: |
        robot --variable BROWSER:headlesschrome Assignment-1-2-4/web/TestCase/Checkout.robot
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: |
          report.html
          log.html
          output.xml 